import csv
import io
import re
from datetime import date, datetime, timezone

from openpyxl import load_workbook

TEMPLATE_COLUMNS = [
    "title",
    "description",
    "owner",
    "status",
    "priority",
    "dependency",
    "next_checkpoint",
    "tags",
    "app_label",
]
UPLOAD_PRIORITIES = {"Low", "Medium", "High", "Urgent", "Critical"}
UPLOAD_STATUSES = {"To Do", "Backlog", "Planned", "In Progress", "Blocked", "In Review", "Done"}
ACTIVE_TASK_STATUSES = {"To Do", "Backlog", "Planned", "In Progress", "Blocked", "In Review"}
MAX_UPLOAD_BYTES = 5 * 1024 * 1024


def template_csv():
    rows = [
        TEMPLATE_COLUMNS,
        ["Review customer feedback", "Analyze recent survey responses", "", "Backlog", "High", "", "Summarize findings", "research;customer", "AISENA Portal"],
        ["Prepare weekly report", "Compile team performance metrics", "documentation-engineer", "Planned", "Medium", "", "Publish the draft", "reporting;weekly", "AISENA Portal"],
        ["Update help content", "Revise outdated onboarding instructions", "", "To Do", "Low", "TASK-000001", "Request content review", "documentation;onboarding", "CRM Portal"],
    ]
    output = io.StringIO(newline="")
    csv.writer(output).writerows(rows)
    return output.getvalue()


def _cell_text(value):
    if value is None:
        return ""
    if isinstance(value, datetime):
        return value.date().isoformat()
    if isinstance(value, date):
        return value.isoformat()
    return str(value).strip()


def _rows_from_csv(content):
    try:
        text = content.decode("utf-8-sig")
    except UnicodeDecodeError as exc:
        raise ValueError("CSV files must use UTF-8 encoding.") from exc
    reader = csv.DictReader(io.StringIO(text))
    if reader.fieldnames is None:
        raise ValueError("The upload must include a header row.")
    headers = [str(header or "").strip() for header in reader.fieldnames]
    rows = [{str(key or "").strip(): _cell_text(value) for key, value in row.items()} for row in reader]
    return headers, rows


def _rows_from_xlsx(content):
    try:
        workbook = load_workbook(io.BytesIO(content), read_only=True, data_only=True)
    except Exception as exc:
        raise ValueError("The XLSX file could not be read.") from exc
    sheet = workbook.active
    values = sheet.iter_rows(values_only=True)
    try:
        headers = [_cell_text(value) for value in next(values)]
    except StopIteration as exc:
        raise ValueError("The upload must include a header row.") from exc
    rows = [dict(zip(headers, (_cell_text(value) for value in row))) for row in values]
    workbook.close()
    return headers, rows


def parse_upload(file_storage):
    filename = (file_storage.filename or "").strip()
    extension = filename.lower().rsplit(".", 1)[-1] if "." in filename else ""
    if extension not in {"csv", "xlsx"}:
        raise ValueError("Upload a CSV or XLSX file.")
    content = file_storage.read(MAX_UPLOAD_BYTES + 1)
    if len(content) > MAX_UPLOAD_BYTES:
        raise ValueError("The upload must be 5 MB or smaller.")
    headers, rows = _rows_from_csv(content) if extension == "csv" else _rows_from_xlsx(content)
    if "task_id" in {header.lower() for header in headers}:
        raise ValueError("The task_id column is not accepted; IDs are generated by the server.")
    unknown = [header for header in headers if header not in TEMPLATE_COLUMNS]
    missing = [header for header in TEMPLATE_COLUMNS if header not in headers]
    if unknown:
        raise ValueError(f"Unknown column(s): {', '.join(unknown)}.")
    if missing:
        raise ValueError(f"Missing template column(s): {', '.join(missing)}.")
    return [row for row in rows if any(_cell_text(value) for value in row.values())]


def _split_values(value):
    if isinstance(value, list):
        values = value
    else:
        values = re.split(r"[;,]", str(value or ""))
    return [str(item).strip().lower() for item in values if str(item).strip()]


def _agent_index(agents):
    index = {}
    for agent in agents:
        index[str(agent.get("key") or "").casefold()] = agent
        index[str(agent.get("name") or "").casefold()] = agent
    return index


def _eligible(agent):
    return (
        bool(agent.get("active", True))
        and bool(agent.get("available", True))
        and bool(agent.get("runtime_available", True))
    )


def _last_assigned_sort_value(value):
    if not value:
        return datetime.min.replace(tzinfo=timezone.utc)
    if isinstance(value, datetime):
        parsed = value
    else:
        try:
            parsed = datetime.fromisoformat(str(value).replace("Z", "+00:00"))
        except ValueError:
            return datetime.min.replace(tzinfo=timezone.utc)
    return parsed.replace(tzinfo=parsed.tzinfo or timezone.utc)


def build_preview(rows, existing_tasks, agents):
    agent_index = _agent_index(agents)
    workloads = {agent.get("key"): 0 for agent in agents}
    last_assigned = {agent.get("key"): agent.get("last_assigned_at") for agent in agents}
    for task in existing_tasks:
        owner = task.get("owner")
        if owner in workloads and task.get("status") in ACTIVE_TASK_STATUSES:
            workloads[owner] += 1

    existing_ids = {str(task.get("id") or "").strip().casefold() for task in existing_tasks}
    existing_titles = {str(task.get("title") or "").strip().casefold() for task in existing_tasks}
    batch_titles = set()
    preview = []

    for row_number, source in enumerate(rows, start=2):
        row = {column: _cell_text(source.get(column)) for column in TEMPLATE_COLUMNS}
        errors = []
        warnings = []
        title = row["title"]
        priority = row["priority"] or "Medium"
        status = row["status"] or "Backlog"
        dependency = row["dependency"]
        tags = _split_values(source.get("tags"))

        if not title:
            errors.append("Title is required.")
        if priority not in UPLOAD_PRIORITIES:
            errors.append("Priority must be Low, Medium, High, Urgent, or Critical.")
        if status not in UPLOAD_STATUSES:
            errors.append("Status must match an option in the New Task form.")
        if dependency and dependency.casefold() not in existing_ids:
            errors.append("Dependency must reference an existing task ID.")

        title_key = title.casefold()
        duplicate = bool(title_key and (title_key in existing_titles or title_key in batch_titles))
        if duplicate:
            warnings.append("Possible duplicate title; this row will be skipped if the match still exists at import time.")
        if title_key:
            batch_titles.add(title_key)

        supplied_assignee = row["owner"]
        assigned_key = ""
        assignment_method = "automatic"
        assignment_required = False
        if supplied_assignee:
            assignment_method = source.get("assignment_method") or "supplied"
            agent = agent_index.get(supplied_assignee.casefold())
            if agent is None:
                errors.append("Owner does not exist.")
            elif not _eligible(agent):
                errors.append("Owner must be active and available.")
            else:
                assigned_key = agent.get("key")
        elif not errors:
            eligible = [agent for agent in agents if _eligible(agent)]
            eligible.sort(key=lambda agent: (
                workloads.get(agent.get("key"), 0),
                _last_assigned_sort_value(last_assigned.get(agent.get("key"))),
                agent.get("key") or "",
            ))
            if eligible:
                agent = eligible[0]
                assigned_key = agent.get("key")
                workloads[assigned_key] = workloads.get(assigned_key, 0) + 1
                last_assigned[assigned_key] = datetime.now(timezone.utc).isoformat()
            else:
                assignment_required = True
                warnings.append("Assignment Required: no active and available owner was found.")

        preview.append({
            "row_number": row_number,
            "title": title,
            "description": row["description"],
            "owner": assigned_key,
            "status": status,
            "priority": priority,
            "dependency": dependency or None,
            "next_checkpoint": row["next_checkpoint"],
            "tags": tags,
            "app_label": row["app_label"] or None,
            "assignment_method": assignment_method,
            "assignment_required": assignment_required,
            "duplicate": duplicate,
            "errors": errors,
            "warnings": warnings,
        })
    return preview
