const ISSUE_SEVERITIES = ["Low", "Medium", "High", "Critical"];
const ISSUE_STATUSES = ["Open", "Triaged", "Mitigating", "Monitoring", "Verifying", "Resolved"];
const LIFECYCLE = ["Report", "Triage", "Mitigate", "Verify"];
const issueId = new URLSearchParams(window.location.search).get("id");
let agentsCache = [], currentIssue = null;

function escapeHtml(value) { const div = document.createElement("div"); div.textContent = value || ""; return div.innerHTML; }
function formatTimestamp(value) { if (!value) return "-"; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleString(); }
function ownerLabel(key) { return agentsCache.find((a) => a.key === key)?.name || key || "Unassigned"; }
async function fetchIssue() { const response = await fetch(`${API_BASE}/api/issues/${encodeURIComponent(issueId)}`, { cache: "no-store" }); return response.ok ? response.json() : null; }
function lifecycleIndex(status) { return status === "Open" ? 0 : status === "Triaged" ? 1 : status === "Resolved" ? 3 : 2; }
function renderHeader() { document.getElementById("issueHeading").textContent = `${currentIssue.id}: ${currentIssue.title}`; document.getElementById("issueSubtitle").textContent = `${currentIssue.status} • ${currentIssue.severity} severity • Owner: ${ownerLabel(currentIssue.owner)}`; document.getElementById("issueCreatedAt").textContent = formatTimestamp(currentIssue.created_at); document.getElementById("issueUpdatedAt").textContent = formatTimestamp(currentIssue.updated_at); }
function renderFields() { document.getElementById("fieldTitle").value = currentIssue.title || ""; document.getElementById("fieldDescription").value = currentIssue.description || ""; document.getElementById("fieldSeverity").innerHTML = ISSUE_SEVERITIES.map((s) => `<option>${s}</option>`).join(""); document.getElementById("fieldSeverity").value = currentIssue.severity; document.getElementById("fieldOwner").innerHTML = agentsCache.map((a) => `<option value="${a.key}">${a.name}</option>`).join(""); document.getElementById("fieldOwner").value = currentIssue.owner; document.getElementById("fieldStatus").innerHTML = ISSUE_STATUSES.map((s) => `<option>${s}</option>`).join(""); document.getElementById("fieldStatus").value = currentIssue.status; document.getElementById("fieldMitigation").value = currentIssue.mitigation || ""; document.getElementById("fieldRelatedTask").value = currentIssue.related_task || ""; document.getElementById("fieldEscalation").checked = Boolean(currentIssue.escalation_flag); }
function renderStepper() { const index = lifecycleIndex(currentIssue.status); document.getElementById("issueStepper").innerHTML = LIFECYCLE.map((step, i) => `<div class="step-badge ${i === index ? "active" : ""}"><span class="step-num">${i + 1}</span><span class="step-label">${step}</span></div>`).join(""); document.getElementById("issueEscalationNotice").textContent = currentIssue.escalation_flag ? "Escalation required: production, legal exposure, pricing, or user data handling is affected." : "No escalation trigger recorded."; }
function renderActivity() { const root = document.getElementById("activityLog"); const entries = (currentIssue.activity_log || []).slice().reverse(); root.innerHTML = entries.length ? entries.map((a) => `<div class="activity-entry"><time>${formatTimestamp(a.timestamp)} • ${escapeHtml(a.actor || "system")}</time>${escapeHtml(a.details || a.action)}</div>`).join("") : "<p>No activity yet.</p>"; }
function renderComments() { const root = document.getElementById("commentThread"); root.innerHTML = (currentIssue.comments || []).length ? currentIssue.comments.map((c) => `<div class="comment-entry"><div class="comment-meta"><span>${escapeHtml(c.author || "User")}</span><span>${formatTimestamp(c.timestamp)}</span></div><p>${escapeHtml(c.text)}</p></div>`).join("") : "<p>No comments yet.</p>"; }
async function reloadIssue() { currentIssue = await fetchIssue(); if (!currentIssue) return; renderHeader(); renderFields(); renderStepper(); renderActivity(); renderComments(); }
async function saveFields() { const status = document.getElementById("issueSaveStatus"); status.textContent = "Saving..."; const payload = { title: document.getElementById("fieldTitle").value.trim(), description: document.getElementById("fieldDescription").value.trim(), severity: document.getElementById("fieldSeverity").value, owner: document.getElementById("fieldOwner").value, status: document.getElementById("fieldStatus").value, mitigation: document.getElementById("fieldMitigation").value.trim(), related_task: document.getElementById("fieldRelatedTask").value.trim() || null, escalation_flag: document.getElementById("fieldEscalation").checked, actor: "User" }; try { const response = await fetch(`${API_BASE}/api/issues/${encodeURIComponent(issueId)}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Save failed"); currentIssue = result.issue || result; renderHeader(); renderStepper(); renderActivity(); status.textContent = "Saved."; } catch (error) { status.textContent = `Save failed: ${error.message}`; } }
async function postComment(author, text) { const response = await fetch(`${API_BASE}/api/issues/${encodeURIComponent(issueId)}/comments`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ author, text }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Comment failed"); currentIssue = result.issue; renderComments(); renderActivity(); renderHeader(); }
function buildContext() { return `Issue ${currentIssue.id}: ${currentIssue.title}\nStatus: ${currentIssue.status} | Severity: ${currentIssue.severity} | Owner: ${ownerLabel(currentIssue.owner)}\nDescription: ${currentIssue.description || "None"}\nMitigation: ${currentIssue.mitigation || "None"}\nEscalation: ${currentIssue.escalation_flag ? "Required" : "No"}\nRelated task: ${currentIssue.related_task || "None"}\nComments:\n${(currentIssue.comments || []).map((c) => `- ${c.author}: ${c.text}`).join("\n") || "None"}\nActivity:\n${(currentIssue.activity_log || []).map((a) => `- ${a.actor}: ${a.details || a.action}`).join("\n") || "None"}`; }
function renderChatMessage(message) { const root = document.getElementById("chatMessages"); const node = document.createElement("div"); node.className = `msg ${message.role}`; node.textContent = message.text; root.appendChild(node); if (message.role === "assistant") { const button = document.createElement("button"); button.className = "ghost"; button.textContent = "Post to comment thread"; button.onclick = async () => { button.disabled = true; try { await postComment(`${ownerLabel(document.getElementById("chatAgentSelect").value)} (AI)`, message.text); button.textContent = "Posted"; } catch (error) { button.disabled = false; window.alert(error.message); } }; root.appendChild(button); } root.scrollTop = root.scrollHeight; }
function initChat() { const select = document.getElementById("chatAgentSelect"); select.innerHTML = agentsCache.map((a) => `<option value="${a.key}">${a.name}</option>`).join(""); select.value = agentsCache.some((a) => a.key === currentIssue.owner) ? currentIssue.owner : agentsCache[0]?.key || ""; renderChatMessage({ role: "system", text: `Ask about ${currentIssue.id}. Responses use the current issue state and audit history.` }); const input = document.getElementById("chatInput"), send = document.getElementById("sendChat"); async function sendMessage() { const text = input.value.trim(), agent = agentsCache.find((a) => a.key === select.value); if (!text || !agent) return; renderChatMessage({ role: "user", text }); input.value = ""; send.disabled = true; try { const response = await fetch(`${API_BASE}/api/agents/${agent.key}/message`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message: `${buildContext()}\n\nQuestion: ${text}\n\nAnswer concisely and only from the issue data above.`, tool_actions: [] }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Agent request failed"); renderChatMessage({ role: "assistant", text: result.reply }); } catch (error) { renderChatMessage({ role: "assistant", text: `${agent.name}: ${error.message}` }); } finally { send.disabled = false; } } send.onclick = sendMessage; input.onkeydown = (event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); sendMessage(); } }; document.getElementById("clearChat").onclick = () => { document.getElementById("chatMessages").innerHTML = ""; }; }
async function initIssuePage() { if (!issueId) { document.getElementById("issueHeading").textContent = "Missing issue id"; return; } agentsCache = await loadAgentCatalog(); await reloadIssue(); if (!currentIssue) { document.getElementById("issueHeading").textContent = `${issueId} not found`; return; } document.getElementById("saveIssueFields").onclick = saveFields; document.getElementById("commentForm").onsubmit = async (event) => { event.preventDefault(); const text = document.getElementById("commentText").value.trim(); if (!text) return; try { await postComment("User", text); document.getElementById("commentText").value = ""; } catch (error) { window.alert(error.message); } }; initChat(); }
initIssuePage();