#!/usr/bin/env python3
"""Extract a clean application-only tree with Sena shop paths removed.

Repeatable on demand. Does not push to a remote; writes a local directory
(or optional tarball) ready for independent build/deploy review.

Usage:
  python3 scripts/extract_application_repo.py --output /tmp/app-extract
  python3 scripts/extract_application_repo.py --output /tmp/app-extract --tarball
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
import tarfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "project" / "extraction" / "APPLICATION_PATHS.json"


def load_manifest() -> dict:
    if not MANIFEST.is_file():
        raise FileNotFoundError(f"Manifest missing: {MANIFEST}")
    return json.loads(MANIFEST.read_text(encoding="utf-8"))


def should_skip(rel: Path, exclude_prefixes: list[str]) -> bool:
    s = rel.as_posix()
    for prefix in exclude_prefixes:
        p = prefix.rstrip("/")
        if s == p or s.startswith(p + "/"):
            return True
    return False


def extract(output: Path, *, dry_run: bool = False) -> list[str]:
    manifest = load_manifest()
    include = manifest.get("include") or []
    exclude = manifest.get("exclude_always") or []
    copied: list[str] = []

    if not dry_run:
        if output.exists():
            shutil.rmtree(output)
        output.mkdir(parents=True)

    for item in include:
        src = ROOT / item
        if not src.exists():
            print(f"WARN: include path missing, skip: {item}", file=sys.stderr)
            continue
        rel = Path(item)
        if should_skip(rel, exclude):
            print(f"WARN: include path is excluded by policy, skip: {item}", file=sys.stderr)
            continue
        dest = output / item
        if dry_run:
            copied.append(item)
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        if src.is_dir():
            shutil.copytree(
                src,
                dest,
                ignore=shutil.ignore_patterns(
                    ".git",
                    "__pycache__",
                    "node_modules",
                    ".venv",
                    "venv",
                    "*.pyc",
                ),
                dirs_exist_ok=True,
            )
        else:
            shutil.copy2(src, dest)
        copied.append(item)

    # Ensure no excluded top-level paths leaked
    if not dry_run and output.exists():
        for prefix in exclude:
            leak = output / prefix
            if leak.exists():
                if leak.is_dir():
                    shutil.rmtree(leak)
                else:
                    leak.unlink()

    readme = output / "EXTRACT_README.md"
    if not dry_run:
        readme.write_text(
            "# Application extract (Sena removed)\n\n"
            "This tree was generated by `scripts/extract_application_repo.py`.\n"
            "It must not contain AISENA shop paths (agents/, project/, docs governance, orchestrator, etc.).\n\n"
            "Next steps:\n"
            "1. Review include list in `project/extraction/APPLICATION_PATHS.json`.\n"
            "2. Install dependencies and run application smoke tests.\n"
            "3. Deploy only after human go-ahead (no continuous deployment).\n",
            encoding="utf-8",
        )
        copied.append("EXTRACT_README.md")

    return copied


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True, help="Destination directory")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--tarball", action="store_true", help="Also write output.tar.gz beside the directory")
    args = parser.parse_args()

    copied = extract(args.output, dry_run=args.dry_run)
    print(f"Extracted {len(copied)} path(s) -> {args.output}")
    for c in copied:
        print(f"  - {c}")

    if args.tarball and not args.dry_run:
        tar_path = args.output.with_suffix(".tar.gz")
        with tarfile.open(tar_path, "w:gz") as tar:
            tar.add(args.output, arcname=args.output.name)
        print(f"Tarball: {tar_path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
